name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.1.0
    - name: Run a one-line script
      run: npm test
