name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    # Requried by react-scripts to know this is a CI environment.
    env:
      CI: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Perform full build
      run: npm run build
